version: "3"

services:
  postgres1:
    image: postgres
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: postgres1
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin1:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: idreesadam200@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8002
    ports:
      - "8002:8002"
    depends_on:
      - postgres1

volumes:
  postgres-data:
